name: preview
on: pull_request

jobs:
  update:
    name: Publish previews on pull requests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: ğŸ—Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: ğŸ—Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ—Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn

      - name: ğŸ—Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ—Install dependencies
        run: yarn install

      - name: ğŸš€ Create Preview Update
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          BRANCH_NAME="pr-${PR_NUMBER}"
          COMMIT_MESSAGE="Preview update for PR #${PR_NUMBER}"
          eas update --branch $BRANCH_NAME --auto --non-interactive --message "$COMMIT_MESSAGE"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
